/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sun Apr 28 10:57:50 2013"
#define BUILD_TIME (1367130470L)

#define VERSION_NUMBER 0x03050300UL
#define VERSION_FEATURES 0x001e0cceUL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x22218188UL
#define VERSION_SANITY2 0xb08195e8UL

#define VERSION_STRING "3.5.3"
#define VERSION_ID \
 "Unix UnNetHack Version 3.5.3 - last build Sun Apr 28 10:57:50 2013."

