/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Thu May 30 10:32:28 2013"
#define BUILD_TIME (1369893748L)

#define VERSION_NUMBER 0x05000000UL
#define VERSION_FEATURES 0x001e0cceUL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x2421d1a3UL
#define VERSION_SANITY2 0xbc91d610UL

#define VERSION_STRING "5.0.0"
#define VERSION_ID \
 "Unix UnNetHack Version 5.0.0 - last build Thu May 30 10:32:28 2013."

